import {
	odinRecipes,
	landingPage,
	rockPaperScissors,
	adminDashboard,
	battleship,
	calculator,
	etchASketch,
	restaurant,
	signupForm,
	ticTacToe,
	todoList,
	weatherApp,
} from '../images/screenshot/';

export const projectData = [
	{
		id: 1,
		title: 'Odin Recipes',
		desc: 'A simple static page created with basic HTML and CSS.',
		link: 'https://github.com/jameschen215/odin-recipes',
		demo: 'https://jameschen215.github.io/odin-recipes',
		image: odinRecipes,
	},
	{
		id: 2,
		title: 'Landing Page',
		desc: 'A foundation course assignment of the Odin Project, which is good practice of flex-box layout.',
		link: 'https://github.com/jameschen215/landing-page',
		demo: 'https://jameschen215.github.io/landing-page',
		image: landingPage,
	},

	{
		id: 3,
		title: 'Rock Paper Scissors',
		desc: 'A classic Rock-Paper-Scissors game built with interactive web design, offering a simple yet engaging user experience.',
		link: 'https://github.com/jameschen215/rock-paper-scissors',
		demo: 'https://jameschen215.github.io/rock-paper-scissors',
		image: rockPaperScissors,
	},
	{
		id: 4,
		title: 'Etch-a-Sketch',
		desc: 'A digital Etch-a-Sketch simulator that allows users to create drawings with a retro-inspired interface, blending nostalgia with modern web functionality.',
		link: 'https://github.com/jameschen215/Etch-a-Sketch',
		demo: 'https://jameschen215.github.io/Etch-a-Sketch',
		image: etchASketch,
	},
	{
		id: 5,
		title: 'Calculator',
		desc: 'A sleek, functional calculator built with JavaScript, featuring a clean interface and reliable arithmetic operations for everyday use.',
		link: 'https://github.com/jameschen215/calculator',
		demo: 'https://jameschen215.github.io/calculator',
		image: calculator,
	},
	{
		id: 6,
		title: 'Signup Form',
		desc: 'A simple sign-up form designed with HTML and CSS, showcasing clean aesthetics and user-friendly input validation.',
		link: 'https://github.com/jameschen215/sign-up-form',
		demo: 'https://jameschen215.github.io/sign-up-form',
		image: signupForm,
	},
	{
		id: 7,
		title: 'Admin Dashboard',
		desc: 'A modern Admin Dashboard built with HTML, CSS, and JavaScript, utilizing Flexbox and Grid layouts for a responsive and efficient data management interface.',
		link: 'https://github.com/jameschen215/Admin-Dashboard',
		demo: 'https://jameschen215.github.io/Admin-Dashboard',
		image: adminDashboard,
	},
	{
		id: 8,
		title: 'Tic-Tac-Toe',
		desc: 'A concise Tic-Tac-Toe game built with JavaScript, using Factory Functions and the Module Pattern for a modular, fun two-player experience.',
		link: 'https://github.com/jameschen215/Tic-Tac-Toe',
		demo: 'https://jameschen215.github.io/Tic-Tac-Toe',
		image: ticTacToe,
	},

	{
		id: 9,
		title: 'Restaurant',
		desc: 'A sleek Restaurant webpage crafted with HTML, CSS, and Webpack, demonstrating efficient module bundling and a polished design for a seamless dining experience.',
		link: 'https://github.com/jameschen215/Restaurant',
		demo: 'https://jameschen215.github.io/Restaurant',
		image: restaurant,
	},
	{
		id: 10,
		title: 'Todo List',
		desc: 'A practical To-Do List application built with JavaScript, leveraging Object-Oriented Programming principles to deliver a clean, organized, and interactive task management experience.',
		link: 'https://github.com/jameschen215/to-do-list',
		demo: 'https://jameschen215.github.io/to-do-list',
		image: todoList,
	},
	{
		id: 11,
		title: 'Weather App',
		desc: 'A dynamic Weather App developed with JavaScript, utilizing asynchronous programming and APIs to provide real-time weather updates with a user-friendly interface.',
		link: 'https://github.com/jameschen215/weather-app',
		demo: 'https://jameschen215.github.io/weather-app',
		image: weatherApp,
	},
	{
		id: 12,
		title: 'Battleship',
		desc: 'A strategic Battleship game built with JavaScript, employing Test-Driven Development (TDD) to ensure robust functionality and an engaging player experience.',
		link: 'https://github.com/jameschen215/battleship',
		demo: 'https://jameschen215.github.io/battleship',
		image: battleship,
	},
];
